Operation = "merge" # merge or split or both

[Merge]
InputFolder = "/go-workspace/pdf-operation/sample"
OutputFolder = "output"
OutputFile = "output.pdf"

[Split]
InputFile = "../sample/65-可可爺爺.pdf"
Pages = "2-3,5-6" # 不能有空白鍵
OutputFolder = "split_out"

